
os: linux
sudo: required
language:
- minimal
services:
- docker

jobs:
    include:
        - name: "checks"
          script:
            - chmod 755 scripts/*.sh
            - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/checks.sh

notifications:
    email: false
